# Generated by Django 5.0.3 on 2024-03-23 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ap_paterno', models.CharField(max_length=20)),
                ('ap_materno', models.CharField(max_length=20)),
                ('ci', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
                ('usuario', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('dinero', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('amigo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.BigIntegerField()),
                ('dinero', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('O', 'Ocupado'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
            ],
        ),
    ]
