# Generated by Django 5.0.3 on 2024-03-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('amigo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.BigIntegerField()),
                ('dinero', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('O', 'Ocupado'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ap_paterno', models.CharField(max_length=20)),
                ('ap_materno', models.CharField(max_length=20)),
                ('ci', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
                ('usuario', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('dinero', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gusto',
            fields=[
                ('gusto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField(max_length=255)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_gusto', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('interes_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField(max_length=255)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_interes', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('calificacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=100)),
                ('emisor', models.CharField(max_length=20)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.amigo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='amigo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente'),
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('fotografia_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=20)),
                ('estado_fotografia', models.CharField(choices=[('R', 'Revisando'), ('P', 'Pendiente'), ('F', 'Finalizado')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteGusto',
            fields=[
                ('clienteGusto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
                ('gusto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.gusto')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteInteres',
            fields=[
                ('clienteInteres_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.interes')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_alquiler',
            fields=[
                ('solicitud_alquiler_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('minutos', models.IntegerField()),
                ('estado_solicitud', models.CharField(choices=[('E', 'Enviado'), ('A', 'Aceptado'), ('R', 'Rechazado'), ('F', 'Finalizado')], max_length=1)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.amigo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
            ],
        ),
    ]
