# Generated by Django 5.0.3 on 2024-03-23 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='hola', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='kevin@susana.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dinero',
            field=models.BigIntegerField(default=99999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='timestamp_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(default='kevin69', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
