# Generated by Django 5.0.3 on 2024-03-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('calificacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=100)),
                ('emisor', models.CharField(max_length=20)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.amigo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('fotografia_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=20)),
                ('estado_fotografia', models.CharField(choices=[('R', 'Revisando'), ('P', 'Pendiente'), ('F', 'Finalizado')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_alquiler',
            fields=[
                ('solicitud_alquiler_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('minutos', models.IntegerField()),
                ('estado_solicitud', models.CharField(choices=[('E', 'Enviado'), ('A', 'Aceptado'), ('R', 'Rechazado'), ('F', 'Finalizado')], max_length=1)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.amigo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
            ],
        ),
    ]