# Generated by Django 5.0.3 on 2024-03-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0002_calificacion_fotografia_solicitud_alquiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gusto',
            fields=[
                ('gusto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField(max_length=255)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_gusto', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('interes_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField(max_length=255)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('timestamp_interes', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteGusto',
            fields=[
                ('clienteGusto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
                ('gusto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.gusto')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteInteres',
            fields=[
                ('clienteInteres_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.cliente')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigo.interes')),
            ],
        ),
    ]
