# Generated by Django 5.0.3 on 2024-04-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0002_alter_solicitud_alquiler_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_alquiler',
            name='precio',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
