# Generated by Django 5.0.3 on 2024-04-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0003_solicitud_alquiler_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='url',
            new_name='tipoImagen',
        ),
    ]
