# Generated by Django 5.0.3 on 2024-04-17 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0004_rename_url_fotografia_tipoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='imagenBase64',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
