# Generated by Django 5.0.3 on 2024-04-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0007_cliente_codigoverificaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1),
        ),
    ]
