# Generated by Django 5.0.3 on 2024-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0008_alter_cliente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('clave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('codigoVerificaion', models.CharField(blank=True, max_length=5, null=True)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
