# Generated by Django 5.0.3 on 2024-04-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0011_alter_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ap_materno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
