# Generated by Django 5.0.3 on 2024-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0012_alter_cliente_ap_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='codigoVerificaion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
