# Generated by Django 5.0.3 on 2024-05-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo', '0013_alter_codigos_codigoverificaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
